export const AVAILABLE_MODULES = [
  'Dashboard',
  'Leads',
  'Oportunidades',
  'Contacts',
  'Accounts',
  'ProdutoConsorcio',
  'EquipeComercial',
  'Vendedores',
  'VendasConsorcio',
  'Comissoes',
  'ConciliacaoAdministradora',
  'RegrasComissao',
  'Reports',
  'Settings',
  'DadosTeste',
  'GestaoAcessos',
];

export const MODULE_LABELS = {
  Dashboard: 'Painel Geral',
  Leads: 'Prospecção',
  Oportunidades: 'Oportunidades',
  Contacts: 'Clientes',
  Accounts: 'Administradoras',
  ProdutoConsorcio: 'Produtos de Consórcio',
  EquipeComercial: 'Equipes Comerciais',
  Vendedores: 'Vendedores',
  VendasConsorcio: 'Vendas de Consórcio',
  Comissoes: 'Comissões',
  ConciliacaoAdministradora: 'Conciliação',
  RegrasComissao: 'Regras de Comissão',
  Reports: 'Relatórios Gerenciais',
  Settings: 'Configurações',
  DadosTeste: 'Dados de Teste',
  GestaoAcessos: 'Gestão de Acessos',
};

export const ROLE_LABELS = {
  super_admin: 'Super Admin',
  admin_empresa: 'Admin Empresa',
  gestor_comercial: 'Gestor Comercial',
  lider_comercial: 'Líder Comercial',
  gestor_financeiro: 'Gestor Financeiro',
  vendedor: 'Vendedor',
  analista_plataforma: 'Analista Plataforma',
};

export const ROLE_MODULE_DEFAULTS = {
  super_admin: [...AVAILABLE_MODULES],
  admin_empresa: [...AVAILABLE_MODULES],
  gestor_comercial: [
    'Dashboard',
    'Leads',
    'Oportunidades',
    'Contacts',
    'Accounts',
    'ProdutoConsorcio',
    'EquipeComercial',
    'Vendedores',
    'VendasConsorcio',
    'Comissoes',
    'ConciliacaoAdministradora',
    'RegrasComissao',
    'Reports',
  ],
  lider_comercial: [
    'Dashboard',
    'Leads',
    'Oportunidades',
    'Contacts',
    'ProdutoConsorcio',
    'Vendedores',
    'VendasConsorcio',
    'Comissoes',
    'ConciliacaoAdministradora',
    'Reports',
  ],
  gestor_financeiro: [
    'Dashboard',
    'Accounts',
    'ProdutoConsorcio',
    'VendasConsorcio',
    'Comissoes',
    'ConciliacaoAdministradora',
    'RegrasComissao',
    'Reports',
  ],
  vendedor: [
    'Dashboard',
    'Leads',
    'Oportunidades',
    'Contacts',
    'ProdutoConsorcio',
    'VendasConsorcio',
    'Comissoes',
  ],
  analista_plataforma: [
    'Dashboard',
    'Leads',
    'Oportunidades',
    'Contacts',
    'Accounts',
    'ProdutoConsorcio',
    'EquipeComercial',
    'Vendedores',
    'VendasConsorcio',
    'Comissoes',
    'ConciliacaoAdministradora',
    'RegrasComissao',
    'Reports',
  ],
};

export const isAdminRole = (role) => role === 'super_admin' || role === 'admin_empresa';
